pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'bash jenkins/build-images.sh'
                sh 'export $(xargs <.env)'
                sh 'printenv'
            }
	    }
	    stage('Test Server') {
            steps {
                sh 'bash jenkins/test-server.sh'
            }
        }
	    stage('Test Name Generator') {
            steps {
                pip3 install -r 2_name_generator/requirements.txt
                python3 -m pytest --cov=application 2_name_generator/ --cov-report html:cov_html
                sh 'bash jenkins/test-name-generator.sh'
            }
        }
	    stage('Test Stats Generator') {
            steps {
                sh 'bash jenkins/test-stats-generator.sh'
            }
        }
	    stage('Test Members Generator') {
            steps {
                sh 'bash jenkins/test-members-generator.sh'
            }
        }
        stage('Deploy') {
            steps {
                sh 'bash jenkins/deploy.sh'
            }
        }
    }
}