pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'bash jenkins/build-images.sh'
            }
	    }
        stage('Set Env Variables') {
            sh '''
                set -a
                source /home/jenkins/.env
                set +a
            '''
        }   
	    stage('Test Server') {
            steps {
                sh 'bash jenkins/test-server.sh'
            }
        }
	    stage('Test Name Generator') {
            steps {
                sh 'bash jenkins/test-name-generator.sh'
            }
        }
	    stage('Test Stats Generator') {
            steps {
                sh 'bash jenkins/test-stats-generator.sh'
            }
        }
	    stage('Test Members Generator') {
            steps {
                sh 'bash jenkins/test-members-generator.sh'
            }
        }
        stage('Deploy') {
            steps {
                sh 'bash jenkins/deploy.sh'
            }
        }
    }
}