- hosts: jenkins
  become: true
  tasks:  
  - name: "Create .ssh folder on Jenkins VM"
    file: 
      path: /home/jenkins/.ssh/
      mode: "0700"
      state: directory
      group: jenkins
      owner: jenkins
  - name: "Copy private key to Jenkins"
    copy:
      src: ~/.ssh/ansible_id_rsa
      dest: /home/jenkins/.ssh/id_rsa
      owner: jenkins
      group: jenkins
      mode: u=rw,g=,o=
