- hosts: manager-node 
  become: true
  tasks:
  - name: "Create .ssh folder on Swarm VM"
    file: 
      path: /home/jenkins/.ssh/
      mode: "0700"
      state: directory
      group: docker
      owner: jenkins
  - name: "Copy public key to Swarm VM"
    copy:
      src: ~/.ssh/ansible_id_rsa.pub
      dest: /home/jenkins/.ssh/authorized_keys
      owner: jenkins
      group: docker
      mode: u=rw,g=,o=
